% Hannah Payne
% startup.m
% Defines defaults for Matlab to run when it starts
% Mostly for making nicer graphs

disp('Welcome to MATLAB!')
disp('edit startup.m to change startup options.')

% Format how numbers display
format compact
 
% Set stuff
set(0, ...
    'DefaultFigurePaperPositionMode','auto',... % exported figure looks like it does on the screen
    'DefaultFigureColor', 'White', ...          % Figure background white
    'DefaultAxesBox', 'off',...
    'DefaultAxesTickDir', 'out',...
    'DefaultTextFontSize', 8, ...
    'DefaultAxesFontSize', 8, ...
    'DefaultTextFontWeight','normal',...
    'DefaultAxesFontWeight','normal',...
    'DefaultLineLineWidth', 1,...
    'DefaultLineColor', 'k',...
    'DefaultAxesXColor','k',...
    'DefaultAxesYColor','k');

% Load the previous path
load('C:\Users\Public\code\matlab\currfolder.mat')
cd(currfolder)

clear;


